LDFLAGS += -lstdc++ -lcurl -lftdi1
INSTALL_SDK = install_sdk
SDK_INCLUDE = -I /home/mikael/private/ccd-kaf-cdip24/software/include/ -I/usr/include/libftdi1/ 
SDK_LIB = /home/mikael/private/ccd-kaf-cdip24/software/build/libccd_kaf_cdip24.a
